# Site settings
author: Kateryna Strough
title: Generation X: The Ageless Generation
header-img: img/home-bg.png
email: katerynastrough@hotmail.com
copyright_name: Kateryna Strough
description: > # this means to ignore newlines until "baseurl:"
  Why I Chose To Become A Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  stroughk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
